config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:index]

  resources :user, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :requests, only: [:create, :show, :destroy] do
    collection do
      patch :admit
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :pictures do
    member do
      get :liking_users
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  post '/like/:picture_id' => 'likes#like', as: 'like'
  delete '/unlike/:picture_id' => 'likes#unlike', as: 'unlike'


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  get '/search', to: 'user#search'

  # Userログイン時
  authenticated :user do
    root :to => "pictures#index", :as => "authenticated_root"
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get '/:username', to: 'about#index', as: "user_profile"
  get '/:username/following', to: 'about#following', as: "following"
  get '/:username/follower', to: 'about#follower', as: "follower"

  # User非ログイン時
  root "top#index"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  picture_id :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  acts_as_taggable_on :labels # post.label_list が追加される
  acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
  belongs_to :user
  belongs_to :picture
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントを保存するアクションです
  def create
    # ログインユーザーに紐づけてインスタンスを生成
    @comment = current_user.comments.build(comment_params)
    @picture = @comment.picture
    respond_to do |format|
      if @comment.save
        format.html { redirect_to pictures_path, notice: 'コメントを投稿しました' }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to pictures_path, notice: 'コメントを削除しました' }
      format.js { render :index }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:picture_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments_feed.html.erb
<% comments.each do |comment| %>
 <div class="comment-loop">
   <div class="row">
     <div class="col-xs-10">
       <%= link_to user_profile_path(comment.user.username), class: 'username' do %>
          <strong><%= comment.user.name %></strong>
       <% end %>
       <%= comment.content %>
     </div>
     <div class="col-xs-2 text-right">
       <% if current_user.id == comment.user_id %>
         <%= link_to '×', picture_comment_path(picture, comment), class: "delete-comment", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
       <% end %>
     </div>
   </div>
 </div>
<% end %>

app/views/comments/_comments_form.html.erb
<%= form_for([picture,comment], remote: true) do |f| %>
  <%= f.hidden_field :picture_id %>
  <%= f.text_field :content, class: 'form-control mb15 input-comment', placeholder: "コメントを入力" %>
<% end %>

app/views/comments/index.js.erb
$("#pic-all-comments-<%= @comment.picture_id %>").html("<%= j(render 'comments/comments_feed', { comments: @comment.picture.comments, picture: @comment.picture }) %>")
$('.input-comment').val('')