config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:index]

  resources :user, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :requests, only: [:create, :show, :destroy] do
    collection do
      patch :admit
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :pictures do
    member do
      get :liking_users
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  post '/like/:picture_id' => 'likes#like', as: 'like'
  delete '/unlike/:picture_id' => 'likes#unlike', as: 'unlike'


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  get '/search', to: 'user#search'

  # Userログイン時
  authenticated :user do
    root :to => "pictures#index", :as => "authenticated_root"
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get '/:username', to: 'about#index', as: "user_profile"
  get '/:username/following', to: 'about#following', as: "following"
  get '/:username/follower', to: 'about#follower', as: "follower"

  # User非ログイン時
  root "top#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  admin                  :boolean          default(FALSE)
#  uid                    :string           default(""), not null
#  provider               :string           default(""), not null
#  image_url              :string
#  avatar                 :string
#  username               :string
#  secret                 :integer          default(0)
#

class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_many :pictures
  # コメントモデルのアソシエーションを設定
  has_many :comments, dependent: :destroy

  # likesモデルのアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_notes, through: :likes, source: :picture

  # relationshipsとユーザーのアソシエーション
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: 'Relationship', dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  # requestテーブルとユーザーのアソシエーションを設定
  has_many :requests, foreign_key: "sender_id", dependent: :destroy
  has_many :reverse_requests, foreign_key: "recipient_id", class_name: 'Request', dependent: :destroy

  has_many :receive_users, through: :requests, source: :sender
  has_many :send_users, through: :reverse_requests, source: :recipient

  scope :or, -> (email, name, username) do
    where("(users.email = ? OR users.name = ? OR users.username = ?)", email, name, username)
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          username: auth.info.nickname,
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          username:     auth.extra.raw_info.name,
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  # フォローしているかどうかを判別
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  # フォローされているユーザーかを判別
  def followed?(other_user)
    reverse_relationships.find_by(follower_id: other_user.id)
  end

  # フォローをやめる
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def send_request!(to_user)
    requests.create!(recipient_id: to_user.id)
  end

  # リクエストを送ったかユーザーか判別
  def sending?(to_user)
    requests.find_by(recipient_id: to_user.id)
  end

  # リクエストを受け取ったユーザーか判別
  def received?(to_user)
    reverse_requests.find_by(sender_id: to_user.id)
  end

  def unsend(to_user)
    requests.find_by(recipient_id: to_user.id).destroy
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def search
    if params[:by] == 'user'
      @objects = User.where("username like ?", "%" + params[:q] + "%")
    else
      @objects = Picture.where("comment like ?", "%" + params[:q] + "%")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/user_helper.rb
module UserHelper
  def getObject(object)
    return object.username if params[:by] == 'user'
    return image_tag("#{object.avatar.url}") if params[:by] == 'picture'
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/user/_result.html.erb
<% if params[:by] == 'user' %>
  <p class="pic-user-info">
    <%= link_to user_profile_path(getObject(object)), class: 'username' do %>
      <span><%= profile_img(object) %></span>
      <strong><%= getObject(object) %></strong>
      <%= object.name %>
    <% end %>
  </p>
<% elsif params[:by] == 'picture'  %>
  <div class="back">
    <%= link_to picture_path(object.id), class: 'username' do %>
      <%= getObject(object) %>
    <% end %>
  </div>
  <div class="front">
    <p class="mask"></p>
    <div class="content">
      <span><%= fa_icon "heart", class: "fa-lg" %>&nbsp;<%= object.likes.count %></span>
      <%= fa_icon "comment", class: "fa-lg" %>&nbsp;<%= object.comments.count %>
    </div>
  </div>
<% end %>

app/views/user/index.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
  <% @users.each do |user| %>
    <div class="pic-area">
      <p class="pic-user-info">
        <%= link_to user_profile_path(user.username), class: 'username' do %>
          <span><%= profile_img(user) %></span>
          <strong><%= user.username %></strong>
          <%= user.name %>
        <% end %>
      </p>
        <% unless user.secret == 0 %>
          <div class="nothing text-center">
            <h3>このアカウントは非公開です</h3>
            <p>このアカウントの写真や動画を見るには、フォローリクエストを送信してください。</p>
          </div>
        <% else %>
          <div class="row">
            <% user.pictures.limit(3).each do |picture| %>
              <div class="col-sm-4">
                <%= link_to picture_path(picture, username: user.username) do %>
                  <%= image_tag("#{picture.avatar.url}") %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/user/search.html.erb
<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <ul class="nav nav-tabs">
    <li class="<%= isActiveTab('user') %>">
      <%= link_to 'Users', search_path(by: 'user', q: params[:q]) %>
    </li>
    <li class="<%= isActiveTab('picture') %>">
      <%= link_to 'Pictures', search_path(by: 'picture', q: params[:q]) %>
    </li>
  </ul>
  <% @objects.each do |object| %>
    <div class="col-sm-4 object-area">
      <%= render partial: 'result', locals: { object: object } %>
    </div>
  <% end %>
</div>