config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:index]

  resources :user, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :requests, only: [:create, :show, :destroy] do
    collection do
      patch :admit
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :pictures do
    member do
      get :liking_users
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  post '/like/:picture_id' => 'likes#like', as: 'like'
  delete '/unlike/:picture_id' => 'likes#unlike', as: 'unlike'


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  get '/search', to: 'user#search'

  # Userログイン時
  authenticated :user do
    root :to => "pictures#index", :as => "authenticated_root"
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get '/:username', to: 'about#index', as: "user_profile"
  get '/:username/following', to: 'about#following', as: "following"
  get '/:username/follower', to: 'about#follower', as: "follower"

  # User非ログイン時
  root "top#index"

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  avatar     :string
#  user_id    :integer
#

class Picture < ActiveRecord::Base
  acts_as_taggable_on :labels # post.label_list が追加される
  acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
  mount_uploader :avatar, AvatarUploader

  validates :avatar, presence: true
  validates :comment, length: { maximum: 255 }

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]


  def index
    @pictures = Picture.all.order(created_at: :desc)
    @users = User.all
    @num = 0
  end

  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    register_tag(@picture)
    @picture.user_id = current_user.id
    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: '投稿の保存に成功しました' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    # ハッシュタグを別テーブルに登録
    register_tag(@picture)
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: '投稿の更新に成功しました' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '投稿の削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:comment, :avatar)
    end

    def register_tag(picture)
      # ハッシュタグを別テーブルに登録
      if picture.comment.include?("#")
        # スペースが入っている場合は登録しない
        tag_comments = picture.comment.split(" ")
        tags = Array.new
        tag_comments.each{|comment|
          # ハッシュタグがふくまれているもの
          if comment.include?("#")
            tag = comment.split("#")
            tags.push(tag)
          end
        }
      end
      picture.tag_list.add(tags)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def getCommentOne(picture)
    @comment = picture.comments.build
  end

  def getCommentAll(picture)
    @comment = picture.comments
  end

  def getDiffTime(picture)
    require 'active_support'
    now = Time.current.strftime("%y/%m/%d %p %l:%M")
    create_at = picture.created_at.strftime("%y/%m/%d %p %l:%M")
    calc = now - create_at
    @timeDiff = calc
  end
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>
  <div class="field">
    <% if @picture.avatar %>
      <div class="form-photo">
        <%= image_tag("#{@picture.avatar}") %>
      </div>
    <% end %>
    <% if current_page? (new_picture_path) %>
      <%= f.label :画像 %><br>
      <%= f.file_field :avatar, class: 'form-control' %>
      <%= f.hidden_field :avatar_cache %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: 'form-control', placeholder: 'キャプションを書く', rows: 4, id: "photo_comment" %>
  </div>
  <div class="actions">
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/pictures/_picture_like.html.erb
<% if picture.likes.count >= 10 %>
  いいね
  <span id="like-count-<%= picture.id %>">
    <%= picture.likes.count %>
  </span>件
<% else %>
  <% if picture.liking_users.present? %>
    <% if picture.liking_users.count <= 5 %>
      <% picture.liking_users.each do |user| %>
        <%= link_to user_profile_path(user.username), class: 'a-dafault' do %>
          <%= user.username %>さん
        <% end %>
      <% end %>
    <% else %>
      いいね！<%= picture.liking_users.count %>件
    <% end %>
  <% end %>
<% end %>

app/views/pictures/edit.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <h1 id="form-title">投稿を編集する</h1>
  <%= render 'form' %>
  <div class="back text-right">
    <%= link_to '戻る', pictures_path %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <% @pictures.each do |picture| %>
      <% if current_user.following?(picture.user) || picture.user == current_user %>
      <div class="pic-area">
        <div class="pic-user-name">
          <p class="pic-user-info">
            <%= link_to user_profile_path(picture.user.username), class: 'username' do %>
              <span><%= profile_img(picture.user) %></span>
              <%= picture.user.username %>
            <% end %>
          </p>
        </div>
        <div class="pic-photo-area">
          <%= image_tag("#{picture.avatar.url}") %>
        </div>
        <div class="pic-changable-area">
          <div id="pic-likes-<%= picture.id %>" class="pic-likes-area">
            <%= render partial: 'picture_like', locals: { picture: picture } %>
          </div>
          <div class="pic-user-area">
            <% if picture.comment.present? %>
              <strong><%= picture.user.name %></strong>
              <span id="comment-feed-<%= picture.id %>"><%= picture.comment %></span>
            <% end %>
          </div>
          <div id="pic-all-comments-<%= picture.id %>" class="pic-comment-area">
            <%= render partial: 'comments/comments_feed', locals: {comments: getCommentAll(picture), picture: picture} %>
          </div>
          <div id="pic-action-<%= picture.id %>" class="pic-action row">
            <div id="pic-like-<%= picture.id %>" class="col-xs-2 text-cetner">
              <%= render partial: 'likes/link_like', locals: {picture: picture} %>
            </div>
            <div class="col-xs-10">
              <%= render partial: 'comments/comments_form', locals: { picture: picture, comment: getCommentOne(picture)} %>
            </div>
          </div>
          <div class="pic-action-area">
            <% if picture.user == current_user %>
              <%= link_to '', edit_picture_path(picture), class: 'fa fa-pencil-square-o fa-2x' %>
              <%= link_to '', picture, class: 'fa fa-trash-o fa-2x', method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div><!-- pic-changable-area -->
      </div><!-- pic-area -->
      <% end %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
$(function(){
  <% @pictures.each do |picture| %>
    var comment = $("#comment-feed-" + <%= picture.id %>).text();
    var html = [];
    var comp = [];
    var comp_plural = [];
    var comp_normal = [];
    if(comment.match(/#/)) {
        // スペースと改行で分割
        var tag_by_space = comment.split(/\s|\n/);
        tag_by_space.forEach(function(val, index, ar){
          if(val.match(/#/)) {
            // タグがある場合はタグで分割(スペースがない場合)
            var tag = val.split("#");
            if (tag.length > 1) {
              // 分割して複数ある場合
              tag.shift();
              tag.forEach(function(val_tag, index_tag, ar_tag){
                comp_plural = "<a href='/search?by=picture&q=" + val_tag + "'>#" + val_tag + "</a>";
                html.push(comp_plural);
              });
            } else {
              // 1つしかない場合
              comp = "<a href='/search?by=picture&q=" + tag + "'>#" + tag + "</a>";
              html.push(comp);
            }
          } else {
            // タグがない場合
            html.push(" " + val);
          }
        });
      $("#comment-feed-" + <%= picture.id %>).html(html);
    }
  <% end %>
});
</script>

app/views/pictures/new.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
  <div class="row">
    <h1 id="form-title">新規投稿</h1>
    <%= render 'form' %>
    <div class="back text-right">
      <%= link_to '戻る', pictures_path %>
    </div>
  </div>
</div>
<div id="debug"></div>
<!-- <script type="text/javascript">
$("#photo_comment").each(function(){
  $(this).bind('keyup', getTags(this));
});

function getTags(elm){
  var tags = elm;
  return function(){
    if(tags.value.match(/#/)) {
      var slush = /#|¥s/;
      var tag = tags.value.split(slush);
      var tag_last = tag[tag.length - 1];
      $("#debug").text(tag[tag.length - 1]);
    }
  }
}
</script> -->

app/views/pictures/show.html.erb
<div class="photo-detail col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
  <div class="row">
    <div class="photo-area col-sm-6">
      <%= image_tag("#{@picture.avatar}") %>
    </div>
    <div class="col-sm-6 user-area">
      <div class="pic-user-photo">
        <%= link_to user_profile_path(@picture.user.username), class: 'username' do %>
          <span><%= profile_img(@picture.user) %></span>
          <%= @picture.user.username %>
        <% end %>
      </div>
      <div id="pic-likes-<%= @picture.id %>" class="pic-likes">
        <%= render partial: 'picture_like', locals: { picture: @picture } %>
      </div>
      <div class="pic-self-comment">
        <strong><%= @picture.user.name %></strong>
        <span id="comment-feed-<%= @picture.id %>"><%= @picture.comment %></span>
      </div>
      <div id="pic-all-comments-<%= @picture.id %>" class="pic-detail-comments">
        <%= render partial: 'comments/comments_feed', locals: {comments: getCommentAll(@picture), picture: @picture} %>
      </div>
      <div id="pic-action-<%= @picture.id %>" class="pic-detail-action row">
        <div id="pic-like-<%= @picture.id %>" class="col-xs-2 text-center">
          <%= render partial: 'likes/link_like', locals: {picture: @picture} %>
        </div>
        <div class="col-xs-10">
          <%= render partial: 'comments/comments_form', locals: { picture: @picture, comment: getCommentOne(@picture)} %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(function(){
    var comment = $("#comment-feed-" + <%= @picture.id %>).text();
    var html = [];
    var comp = [];
    var comp_plural = [];
    var comp_normal = [];
    if(comment.match(/#/)) {
        // スペースと改行で分割
        var tag_by_space = comment.split(/\s|\n/);
        tag_by_space.forEach(function(val, index, ar){
          if(val.match(/#/)) {
            // タグがある場合はタグで分割(スペースがない場合)
            var tag = val.split("#");
            if (tag.length > 1) {
              // 分割して複数ある場合
              tag.shift();
              tag.forEach(function(val_tag, index_tag, ar_tag){
                comp_plural = "<a href='/search?by=picture&q=" + val_tag + "'>#" + val_tag + "</a>";
                html.push(comp_plural);
              });
            } else {
              // 1つしかない場合
              comp = "<a href='/search?by=picture&q=" + tag + "'>#" + tag + "</a>";
              html.push(comp);
            }
          } else {
            // タグがない場合
            html.push(" " + val);
          }
        });
      $("#comment-feed-" + <%= @picture.id %>).html(html);
    }
});
</script>