config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:index]

  resources :user, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :requests, only: [:create, :show, :destroy] do
    collection do
      patch :admit
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :pictures do
    member do
      get :liking_users
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  post '/like/:picture_id' => 'likes#like', as: 'like'
  delete '/unlike/:picture_id' => 'likes#unlike', as: 'unlike'


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  get '/search', to: 'user#search'

  # Userログイン時
  authenticated :user do
    root :to => "pictures#index", :as => "authenticated_root"
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get '/:username', to: 'about#index', as: "user_profile"
  get '/:username/following', to: 'about#following', as: "following"
  get '/:username/follower', to: 'about#follower', as: "follower"

  # User非ログイン時
  root "top#index"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @user = User.find_by(username: params[:username])
    @pictures = @user.pictures
  end

  def following
    @user = User.find_by(username: params[:username])
    @followings = @user.followed_users
  end

  def follower
    @user = User.find_by(username: params[:username])
    @followers = @user.followers
  end

end

app/helpers/about_helper.rb
module AboutHelper
  def checkPageParams(page)
    page == params[:page] ? "active" : "non-active"
  end
end

app/views/about/_follow_form.html.erb
<% unless current_user.following?(user) %>
  <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true, class: 'follow-form-area') do |f| %>
    <%= f.hidden_field :followed_id %>
    <%= f.submit "フォローする", class: "follow-btn" %>
  <% end %>
<% else %>
  <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true, class: 'follow-form-area') do |f| %>
    <%= f.submit "フォロー中", class: "unfollow-btn" %>
  <% end %>
<% end %>

app/views/about/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= @picture.name %>
  </div>
</div>

app/views/about/_picture_feed.html.erb
<% if user.secret == 1 && !current_user.following?(user) && user != current_user %>
  <div class="nothing text-center">
    <h3>このアカウントは非公開です</h3>
    <p>このアカウントの写真や動画を見るには、フォローリクエストを送信してください。</p>
  </div>
<% else %>
  <% if pictures.blank? %>
    <div class="nothing text-center">
      <h3>投稿はまだありません。</h3>
    </div>
  <% else %>
    <% pictures.each do |picture| %>
      <div class="col-sm-4 picture-item mb25">
        <%= link_to picture_path(picture, username: user.username), class: "no_border" do %>
          <%= image_tag("#{picture.avatar}") %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/about/follower.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="row">
      <div class="col-xs-2 profile-img">
        <h2><%= profile_img(@user) %></h2>
      </div>
      <div class="col-xs-10">
        <h1>
          <%= @user.username %>
          <% if @user.id == current_user.id %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: 'edit-profile' %>
          <% else %>
            <span id="send-request-<%= @user.id %>" class="follow-area">
              <% if @user.secret == 1 && !current_user.following?(@user) %>
                <%= render 'requests/request_form', user: @user %>
              <% else %>
                <%= render 'follow_form', user: @user %>
              <% end %>
            </span>
          <% end %>
        </h1>
        <p><%= @user.name %></p>
      </div>
    </div><!-- row -->
    <div class="follower-area">
      <h3>フォローワー</h3>
      <% @followers.each do |follower| %>
        <div class="follower-list">
          <%= link_to user_profile_path(follower.username) do %>
            <%= follower.name %>
          <% end %>
          <% if current_user.id != follower.id %>
            <span id="send-request-<%= follower.id %>" class="follower-btn">
              <% if follower.secret == 1 && !current_user.following?(follower) %>
                <%= render 'requests/request_form', user: follower %>
              <% else %>
                <%= render 'follow_form', user: follower %>
              <% end %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/about/following.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="row">
      <div class="col-xs-2 profile-img">
        <h2><%= profile_img(@user) %></h2>
      </div>
      <div class="col-xs-10">
        <h1>
          <%= @user.username %>
          <% if @user.id == current_user.id %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: 'edit-profile' %>
          <% else %>
            <span id="send-request-<%= @user.id %>" class="follow-area">
              <% if @user.secret == 1 && !current_user.following?(@user) %>
                <%= render 'requests/request_form', user: @user %>
              <% else %>
                <%= render 'follow_form', user: @user %>
              <% end %>
            </span>
          <% end %>
        </h1>
        <p><%= @user.name %></p>
      </div>
    </div><!-- row -->
    <div class="following-area">
      <h3>フォローしている人</h3>
      <% @followings.each do |following| %>
        <div class="following-list">
          <%= link_to user_profile_path(following.username) do %>
            <%= following.name %>
          <% end %>
          <% if current_user.id != following.id %>
            <span id="send-request-<%= following.id %>" class="following-btn">
              <% if following.secret == 1 && !current_user.following?(following) %>
                <%= render 'requests/request_form', user: following %>
              <% else %>
                <%= render 'follow_form', user: following %>
              <% end %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/about/index.html.erb
<div class="about-area col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
  <div class="row">
    <div class="col-xs-2 profile-img">
      <h2><%= profile_img(@user) %></h2>
    </div>
    <div class="col-xs-10">
      <h1>
        <%= @user.username %>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_registration_path(page: "default"), class: 'edit-profile' %>
        <% else %>
          <span id="send-request-<%= @user.id %>" class="follow-area">
            <% if @user.secret == 1 && !current_user.following?(@user) %>
              <%= render 'requests/request_form', user: @user %>
            <% else %>
              <%= render 'follow_form', user: @user %>
            <% end %>
          </span>
        <% end %>
      </h1>
      <ul class="profile-area">
        <li>投稿<strong><%= @user.pictures.count %></strong>件</li>
        <li>
          <%= link_to follower_path, class: '' do %>
            フォローワー<span id="follower-count"><%= @user.followers.count %></span>人
          <% end %>
        </li>
        <li>
          <%= link_to following_path, class: '' do %>
            <span id="following-count"><%= @user.followed_users.count %></span>人をフォロー中
          <% end %>
        </li>
        <li>
          <% unless @user == current_user %>
            <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post'%>
          <% end %>
        </li>
      </ul>
      <p><%= @user.name %></p>
      <p><%= @user.introduction %></p>
    </div>
  </div>
  <% if @user.secret == 1 && @user == current_user && @user.reverse_requests.count != 0 %>
    <div class="request-count">
      <h4>
        <%= link_to request_path(@user), class: "a-dafault" do %>
          現在のフォローリクエスト<span><%= @user.reverse_requests.count %></span>
        <% end %>
      </h4>
    </div>
  <% end %>
  <div class="picture-area">
    <%= render 'picture_feed', pictures: @pictures, user: @user %>
  </div>
</div>